name: pull request

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - labeled
    - unlabeled
  pull_request_review:
    types:
    - submitted
  check_suite:
    types:
    - complited

jobs:
  pr:
    name: automerge
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_METHOD: squash
